import { Check, ChevronLeft, ChevronRight, Edit3, Eye, Filter, Search } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import type { CardStatus, CuratedCard } from '@/contracts/admin'
import { AlertDialog, AlertDialogContent, AlertDialogTrigger, Badge, Button, Dialog, DialogContent, Input, Label, Textarea } from '@/components/ui'
import { PageHeading } from '@/pages/overview'
import { useAdminStore } from '@/state/admin-store'

export function DeckPage() {
  const { t, i18n } = useTranslation(); const { cards, updateCard, publishReview } = useAdminStore()
  const [query, setQuery] = useState(''); const [status, setStatus] = useState<'all'|CardStatus>('all'); const [selected, setSelected] = useState<string[]>([]); const [editing, setEditing] = useState<CuratedCard | null>(null); const [toast, setToast] = useState('')
  const locale = i18n.language === 'en' ? 'en' : 'zh-TW'
  const filtered = useMemo(() => cards.filter(card => (status === 'all' || card.status === status) && `${card.title.en} ${card.title['zh-TW']} ${card.order}`.toLowerCase().includes(query.toLowerCase())), [cards, query, status])
  const save = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!editing) return; const data = new FormData(event.currentTarget); updateCard({ ...editing, title: { 'zh-TW': String(data.get('zhTitle')), en: String(data.get('enTitle')) }, prompt: { 'zh-TW': String(data.get('zhPrompt')), en: String(data.get('enPrompt')) }, updatedAt: new Date().toISOString() }); setEditing(null); setToast(t('cardSaved')); setTimeout(() => setToast(''), 2500) }
  const toggle = (id: string) => setSelected(current => current.includes(id) ? current.filter(x => x !== id) : [...current, id])
  return <div className="page-enter space-y-6"><PageHeading title={t('deckTitle')} subtitle={t('deckSubtitle')} action={<AlertDialog><AlertDialogTrigger asChild><Button><Check className="h-4 w-4" />{t('publishDeck')}</Button></AlertDialogTrigger><AlertDialogContent title={t('publishConfirmTitle')} description={t('publishConfirmBody')} cancel={t('cancel')} action={t('confirmPublish')} onAction={publishReview} /></AlertDialog>} />
    <div className="overflow-hidden rounded-lg border bg-card"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row sm:items-center"><div className="relative flex-1 sm:max-w-xs"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" /><Input value={query} onChange={e => setQuery(e.target.value)} className="pl-9" placeholder={t('searchHint')} /></div><div className="relative"><Filter className="pointer-events-none absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" /><select aria-label={t('status')} value={status} onChange={e => setStatus(e.target.value as typeof status)} className="h-9 rounded-md border bg-card pl-9 pr-8 text-sm outline-none focus:ring-2 focus:ring-ring/30"><option value="all">{t('filterAll')}</option><option value="published">{t('published')}</option><option value="review">{t('review')}</option><option value="draft">{t('draft')}</option></select></div>{selected.length > 0 && <div className="flex items-center gap-2 sm:ml-auto"><span className="text-xs text-muted-foreground">{t('selectedCount', { count: selected.length })}</span><Button size="sm" variant="outline" onClick={() => { selected.forEach(id => { const card = cards.find(x => x.id === id); if (card) updateCard({ ...card, status: 'review' }) }); setSelected([]) }}>{t('sendReview')}</Button></div>}</div>
      <div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-sm"><thead className="bg-muted/45 text-xs text-muted-foreground"><tr><th className="w-12 px-4 py-2.5"></th><th className="w-16 px-2 py-2.5">#</th><th className="px-3 py-2.5 font-medium">{t('title')}</th><th className="px-3 py-2.5 font-medium">{t('status')}</th><th className="px-3 py-2.5 font-medium">{t('updated')}</th><th className="px-3 py-2.5 font-medium">{t('editor')}</th><th className="px-4 py-2.5 text-right font-medium">{t('actions')}</th></tr></thead><tbody className="divide-y">{filtered.map(card => <tr key={card.id} className="hover:bg-muted/25"><td className="px-4 py-3"><input type="checkbox" checked={selected.includes(card.id)} onChange={() => toggle(card.id)} aria-label={`${t('selectCard')} ${card.order}`} className="h-4 w-4 accent-primary" /></td><td className="px-2 py-3 tabular-nums text-muted-foreground">{String(card.order).padStart(2, '0')}</td><td className="max-w-sm px-3 py-3"><p className="truncate font-medium">{card.title[locale]}</p><p className="mt-0.5 truncate text-xs text-muted-foreground">{card.prompt[locale]}</p></td><td className="px-3 py-3"><StatusBadge status={card.status} /></td><td className="px-3 py-3 text-xs text-muted-foreground">{new Intl.DateTimeFormat(i18n.language, { month: 'short', day: 'numeric' }).format(new Date(card.updatedAt))}</td><td className="px-3 py-3 text-xs">{card.updatedBy}</td><td className="px-4 py-3"><div className="flex justify-end gap-1"><Button variant="ghost" size="icon" aria-label={t('preview')}><Eye className="h-4 w-4" /></Button><Button variant="ghost" size="icon" aria-label={t('edit')} onClick={() => setEditing(card)}><Edit3 className="h-4 w-4" /></Button></div></td></tr>)}</tbody></table>{filtered.length === 0 && <div className="p-12 text-center text-sm text-muted-foreground">{t('empty')}</div>}</div><div className="flex items-center justify-between border-t px-4 py-3 text-xs text-muted-foreground"><span>{filtered.length} / 50 {t('cards').toLowerCase()}</span><div className="flex gap-1"><Button variant="outline" size="icon" disabled><ChevronLeft className="h-4 w-4" /></Button><Button variant="outline" size="icon" disabled><ChevronRight className="h-4 w-4" /></Button></div></div></div>
    <Dialog open={!!editing} onOpenChange={(open) => !open && setEditing(null)}><DialogContent title={t('cardEditor')}><form onSubmit={save} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label={t('zhTitle')}><Input name="zhTitle" defaultValue={editing?.title['zh-TW']} required /></Field><Field label={t('enTitle')}><Input name="enTitle" defaultValue={editing?.title.en} required /></Field></div><Field label={t('zhPrompt')}><Textarea name="zhPrompt" defaultValue={editing?.prompt['zh-TW']} required /></Field><Field label={t('enPrompt')}><Textarea name="enPrompt" defaultValue={editing?.prompt.en} required /></Field><div className="flex justify-end gap-2 border-t pt-4"><Button type="button" variant="outline" onClick={() => setEditing(null)}>{t('cancel')}</Button><Button type="submit">{t('saveCard')}</Button></div></form></DialogContent></Dialog>{toast && <div role="status" className="fixed bottom-5 right-5 rounded-md bg-primary px-4 py-3 text-sm text-primary-foreground shadow-lg">{toast}</div>}</div>
  function StatusBadge({ status }: { status: CardStatus }) { return <Badge tone={status === 'published' ? 'green' : status === 'review' ? 'amber' : 'neutral'}>{t(status)}</Badge> }
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-1.5"><Label>{label}</Label>{children}</div> }
