import { CircleDollarSign, Info, ShieldAlert, User, UserRoundCheck } from 'lucide-react'
import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Button, Card, Input, Label, Progress, Switch } from '@/components/ui'
import { PageHeading } from '@/pages/overview'
import { useAdminStore } from '@/state/admin-store'

export function SettingsPage() {
  const { t } = useTranslation(); const { settings, saveSettings } = useAdminStore(); const [draft, setDraft] = useState(settings); const [saved, setSaved] = useState(false)
  const percent = Math.min(100, Math.round(draft.usedThisMonthUsd / draft.globalMonthlyBudgetUsd * 100))
  const submit = (e: React.FormEvent) => { e.preventDefault(); saveSettings({ ...draft, updatedAt: new Date().toISOString() }); setSaved(true); setTimeout(() => setSaved(false), 2500) }
  return <form onSubmit={submit} className="page-enter space-y-6"><PageHeading title={t('settingsTitle')} subtitle={t('settingsSubtitle')} action={<Button type="submit">{saved ? t('saved') : t('saveChanges')}</Button>} /><div className="grid gap-4 xl:grid-cols-2"><Card className="p-5"><div className="flex items-start gap-3 border-b pb-4"><div className="grid h-9 w-9 place-items-center rounded-md bg-accent"><UserRoundCheck className="h-4 w-4" /></div><div><h2 className="text-sm font-semibold">{t('dailyQuota')}</h2><p className="mt-1 text-xs text-muted-foreground">{t('dailyQuotaHint')}</p></div></div><div className="divide-y"><QuotaRow icon={<User className="h-4 w-4" />} label={t('anonymous')} value={draft.anonymousDaily} onChange={value => setDraft({ ...draft, anonymousDaily: value })} suffix={t('requestsDay')} /><QuotaRow icon={<UserRoundCheck className="h-4 w-4" />} label={t('authenticated')} value={draft.authenticatedDaily} onChange={value => setDraft({ ...draft, authenticatedDaily: value })} suffix={t('requestsDay')} /></div></Card><Card className="p-5"><div className="flex items-start gap-3 border-b pb-4"><div className="grid h-9 w-9 place-items-center rounded-md bg-accent"><CircleDollarSign className="h-4 w-4" /></div><div><h2 className="text-sm font-semibold">{t('globalBudget')}</h2><p className="mt-1 text-xs text-muted-foreground">{t('globalBudgetHint')}</p></div></div><div className="space-y-5 pt-5"><div className="space-y-1.5"><Label htmlFor="budget">{t('monthlyLimit')}</Label><div className="relative max-w-xs"><span className="absolute left-3 top-2.5 text-sm text-muted-foreground">$</span><Input id="budget" type="number" min="1" step="1" required value={draft.globalMonthlyBudgetUsd} onChange={e => setDraft({ ...draft, globalMonthlyBudgetUsd: Math.max(1, Number(e.target.value)) })} className="pl-7" /></div></div><div className="flex items-center justify-between gap-4 rounded-md border bg-muted/25 p-4"><div><Label>{t('cutoff')}</Label><p className="mt-1 text-xs text-muted-foreground">{t('cutoffHint')}</p></div><Switch checked={draft.budgetCutoffEnabled} onCheckedChange={value => setDraft({ ...draft, budgetCutoffEnabled: value })} aria-label={t('cutoff')} /></div><div><div className="mb-2 flex justify-between text-xs"><span className="text-muted-foreground">{t('currentUsage')}</span><span className="font-medium">US${draft.usedThisMonthUsd.toFixed(2)} / ${draft.globalMonthlyBudgetUsd.toFixed(2)}</span></div><Progress value={percent} /><p className="mt-2 text-right text-xs text-muted-foreground">{percent}%</p></div></div></Card></div><div className="flex gap-3 rounded-lg border border-amber-200 bg-amber-50 p-4 text-amber-900"><ShieldAlert className="mt-0.5 h-4 w-4 shrink-0" /><div><p className="text-sm font-medium">{t('auditNote')}</p><p className="mt-1 text-xs text-amber-800">{t('auditDetail')}</p></div></div></form>
}
function QuotaRow({ icon, label, value, onChange, suffix }: { icon: React.ReactNode; label: string; value: number; onChange: (value: number) => void; suffix: string }) { return <div className="flex items-center gap-3 py-5"><div className="grid h-8 w-8 place-items-center rounded-md bg-muted text-muted-foreground">{icon}</div><Label className="flex-1">{label}</Label><Input aria-label={label} className="w-20 text-right tabular-nums" type="number" min="0" max="100" required value={value} onChange={e => onChange(Math.max(0, Number(e.target.value)))} /><span className="w-24 text-xs text-muted-foreground">{suffix}</span></div> }
