import { createContext,useCallback,useContext,useEffect,useMemo,useState,type ReactNode } from 'react'
import type { AdminUser,CuratedCard,QuotaSettings } from '@/contracts/admin'
import { useAdminAuth } from '@/auth/auth'; import { adminRequest } from '@/lib/api'
type Batch={id:string;title:string;status:'draft'|'published';createdAt:string}
type ApiCard={id:string;position:number;zh:string;en:string;imagePrompt?:string|null;status:'pending'|'approved'|'rejected';updatedAt:string}
type ApiUser={id:string;displayName?:string;email?:string;role:'admin'|'user'|'future';updatedAt:string}
type Store={cards:CuratedCard[];users:AdminUser[];settings:QuotaSettings;loading:boolean;error:string;updateCard:(c:CuratedCard)=>Promise<void>;publishReview:()=>Promise<void>;updateUser:(u:AdminUser)=>void;saveSettings:(s:QuotaSettings)=>Promise<void>;reload:()=>Promise<void>}
const Context=createContext<Store|null>(null); const defaults:QuotaSettings={anonymousDaily:1,authenticatedDaily:3,globalMonthlyBudgetUsd:100,budgetCutoffEnabled:true,usedThisMonthUsd:0,updatedAt:new Date(0).toISOString()}
export function AdminStoreProvider({children}:{children:ReactNode}){const auth=useAdminAuth();const[cards,setCards]=useState<CuratedCard[]>([]);const[users,setUsers]=useState<AdminUser[]>([]);const[settings,setSettings]=useState(defaults);const[batches,setBatches]=useState<Batch[]>([]);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const token=auth.accessToken
 const reload=useCallback(async()=>{if(!token)return;setLoading(true);setError('');try{const bs=await adminRequest<Batch[]>('/api/batches',token);setBatches(bs);const active=bs.at(-1);const raw=active?await adminRequest<ApiCard[]>(`/api/batches/${active.id}/cards`,token):[];setCards(raw.map(c=>({id:c.id,order:c.position+1,title:{'zh-TW':c.zh,en:c.en},prompt:{'zh-TW':c.imagePrompt||'',en:c.imagePrompt||''},status:active?.status==='published'&&c.status==='approved'?'published':c.status==='approved'?'review':'draft',updatedAt:c.updatedAt,updatedBy:'—'})));const us=await adminRequest<ApiUser[]>('/api/users',token);setUsers(us.map(u=>({id:u.id,name:u.displayName||u.email||u.id,email:u.email||'',roles:[u.role==='admin'?'admin':'viewer'],status:'active',lastActiveAt:u.updatedAt})));const s=await adminRequest<{values:Record<string,unknown>;usedUnits:number;updatedAt:string}>('/api/settings',token);setSettings({anonymousDaily:Number(s.values.anonymous_daily_quota??1),authenticatedDaily:Number(s.values.authenticated_daily_quota??3),globalMonthlyBudgetUsd:Number(s.values.global_budget_units??100),budgetCutoffEnabled:Boolean(s.values.budget_cutoff_enabled??true),usedThisMonthUsd:s.usedUnits,updatedAt:s.updatedAt})}catch(e){setError(e instanceof Error?e.message:'Request failed')}finally{setLoading(false)}},[token]);useEffect(()=>{void reload()},[reload]);
 const updateCard=async(card:CuratedCard)=>{if(!token)throw new Error('Missing token');await adminRequest(`/api/cards/${card.id}/review`,token,{method:'PATCH',body:JSON.stringify({zh:card.title['zh-TW'],en:card.title.en,imagePrompt:card.prompt.en,status:card.status==='draft'?'rejected':'approved'})});await reload()};const publishReview=async()=>{const active=batches.at(-1);if(!token||!active)throw new Error('No batch');await adminRequest(`/api/batches/${active.id}/publish`,token,{method:'POST'});await reload()};const saveSettings=async(next:QuotaSettings)=>{if(!token)throw new Error('Missing token');for(const[key,value]of Object.entries({anonymous_daily_quota:next.anonymousDaily,authenticated_daily_quota:next.authenticatedDaily,global_budget_units:next.globalMonthlyBudgetUsd,budget_cutoff_enabled:next.budgetCutoffEnabled}))await adminRequest(`/api/settings/${key}`,token,{method:'PUT',body:JSON.stringify({value})});await reload()};const value=useMemo<Store>(()=>({cards,users,settings,loading,error,updateCard,publishReview,updateUser:()=>{},saveSettings,reload}),[cards,users,settings,loading,error,reload]);return <Context.Provider value={value}>{children}</Context.Provider>}
export function useAdminStore(){const value=useContext(Context);if(!value)throw new Error('Missing AdminStoreProvider');return value}
